// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Xtx.Entity.NetCoreDemoDb
{
    public partial class SysMenu
    {
        public string SysMenuId { get; set; }
        public string ParentId { get; set; }
        public string MenuPath { get; set; }
        public string MenuName { get; set; }
        public string MenuIcon { get; set; }
        public string Identity { get; set; }
        public string RouteUrl { get; set; }
        public bool Visible { get; set; }
        public bool Active { get; set; }
        public int SortIndex { get; set; }
    }
}