// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Xtx.Entity.NetCoreDemoDb
{
    public partial class SysRole
    {
        public string SysRoleId { get; set; }
        public string SysRoleName { get; set; }
        public int ParentId { get; set; }
        public string NodePath { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedDateTime { get; set; }
    }
}