// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Zxw.Framework.NetCore.Models;

#nullable disable

namespace Xtx.Entity.NetCoreDemoDb
{
    public partial class SysUser:BaseModel<string>
    {
        public override string Id { get; set; }
        public string SysUserId { get; set; }
        public string SysUserName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string SysPassword { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public DateTime? LatestLoginDateTime { get; set; }
        public string LatestLoginIp { get; set; }
    }
}