// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Xtx.Entity.Db1
{
    /// <summary>
    /// 系统短信模块表
    /// </summary>
    public partial class SystemSms
    {
        /// <summary>
        /// Id
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 短信类型
        /// </summary>
        public int SmsType { get; set; }
        /// <summary>
        /// 来源类型
        /// </summary>
        public int ScourceType { get; set; }
        /// <summary>
        /// 短信内容
        /// </summary>
        public string SmsContent { get; set; }
        /// <summary>
        /// 电话号码
        /// </summary>
        public string PhoneNumber { get; set; }
        
    }
}